name: 'food_price_tracker_indiv'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2
  - altair=5.3
  - vl-convert-python=1.3.0
  - vegafusion=1.6.6
  - country_converter=1.2
  - pip=24.0
  - streamlit
  - plotly
  - pip: 
    - hdx-python-api==6.2.6
